services:
  - type: web
    name: secureapi-api
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_HTTPS
        value: false
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: CLIENT_ORIGIN
        sync: false
      - key: LOKI_HOST
        sync: false
      - key: LOKI_USERNAME
        sync: false
      - key: LOKI_PASSWORD
        sync: false
