sonar.projectKey=iie-INSY7314_LearningUnit6
sonar.organization=iie-insy7314
sonar.projectName=SecureAPI
sonar.sources=api,client/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**
sonar.javascript.lcov.reportPaths=api/coverage/lcov.info
